

BlueWeb.useRevoke = false -- If true, processing a jailable offense or issuing a citation that is marked as "revoke" will remove the associated license from the offender automatically
                         -- If false, officers will have to revoke licenses manually

BlueWeb.allowOver = false -- If true, officers can give jail times or fines above the maximum but will be given a notice that the amount exceeds the maximum value
                         -- If false, officers will be unable to issue times/fines above the maximum limit


--[[ Criminal Codes

    Used for automatic fine detection/calculation

    Minimum & Maximum fines/times are just recommendations.
    Players will enter the fine/time when charging the offense.

    isCapitol = BlueWeb will treat the offense as a Capitol Offense
    isFelony  = BlueWeb will treat the offense as a dangerous / violent crime
    revoke    = BlueWeb will revoke the license

]]

BlueWeb.codes = {
    --["CODE"] = {title = "", isCapitol = true, isFelony = true, revoke = 'licenseName', minTime = 5, maxTime = 12, minFine = 100, maxFine = 1000, description = ""},

    -- Felony Offenses
    ["C101"] = {title = "Murder",       isCapitol = true, isFelony = true, minTime = 1, maxTime = 160, minFine = 0, maxFine = 20000, description = "Unlawful killing of another person AND the killing was committed with malice aforethought OR in the commission of a violent felony where great bodily injury or death is likely"},
    ["C102"] = {title = "Terrorism",    isCapitol = true, isFelony = true, minTime = 1, maxTime = 160, minFine = 0, maxFine = 20000, description = "Use/threat of violence and intimidation for the purpose of political or social objective OR the attempted or actual unlawful killing of 10 or more persons within a 24 hour period"},
    ["C201"] = {title = "Manslaughter", isCapitol = true, isFelony = true, minTime = 1, maxTime = 160, minFine = 0, maxFine = 20000, description = "Unlawful killing of another person without malice aforethought (negligence) OR any unintended death occurring from any arson"},

    ["F101"] = {title = "Aggravated Assault",       isFelony = true, minTime = 1, maxTime = 60, minFine = 0, maxFine = 7000, description = "Intent to cause great bodily injury and/or display of a weapon during an assault OR any Assault on a Government Official OR any Assault of a Domestic Partner"},
    ["F102"] = {title = "Kidnapping",               isFelony = true, minTime = 1, maxTime = 60, minFine = 0, maxFine = 7000, description = "Moving any person against their will to another location through means of force, threat or violence"},
    ["F103"] = {title = "Aggravated Robbery",       isFelony = true, minTime = 1, maxTime = 60, minFine = 0, maxFine = 7000, description = "Theft by means of using a weapon OR theft occurring in an occupied dwelling OR theft from a transit or taxi driver OR theft from a person while using an ATM or bank OR theft resulting in great bodily injury"},
    ["F104"] = {title = "Larceny, 1st Degree",      isFelony = true, minTime = 1, maxTime = 60, minFine = 0, maxFine = 7000, description = "Any series of related thefts resulting in the theft of property valued at $100,000 or greater from a single entity or person"},
    ["F105"] = {title = "Escape Detention",         isFelony = true, minTime = 1, maxTime = 60, minFine = 0, maxFine = 7000, description = "Escaping or assisting a person to escape the detention from any jail, rehabilitation or prison facility without lawful authority or release"},
    ["F106"] = {title = "Launder, 1st Degree",      isFelony = true, minTime = 1, maxTime = 60, minFine = 0, maxFine = 7000, description = "Concealing, disguising or processing unlawfully obtained property of monetary value resulting in proceeds of $100,000 or more from any series of related events"},
    ["F107"] = {title = "Sale of Marijuana, 99u",   isFelony = true, minTime = 1, maxTime = 60, minFine = 0, maxFine = 7000, description = "Illegally possessing, harboring, distributing or transporting of Marijuana of 3.51oz (99 units) or more"},
    ["F108"] = {title = "Sale of Narcotics, 100u",  isFelony = true, minTime = 1, maxTime = 60, minFine = 0, maxFine = 7000, description = "Illegally possessing, harboring, distributing or transporting of any Schedule 1 narcotic equal or in excess of 100 units"},
    ["F109"] = {title = "Felon Possess Firearm",    isFelony = true, minTime = 1, maxTime = 60, minFine = 0, maxFine = 7000, description = "Any previously convicted felon, whereas their felony has not been expunged, possesses any firearm or is in close proximity to any uncontrolled firearm. For the purposes of this section, an uncontrolled firearm is a firearm not in another persons immediate possession."},

    ["F201"] = {title = "Launder, 2nd Degree",      isFelony = true, minTime = 1, maxTime = 45, minFine = 0, maxFine = 6000, description = "Concealing, disguising or processing unlawfully obtained property of monetary value resulting in proceeds of $75,000 or more from any series of related events"},
    ["F202"] = {title = "Larceny, 2nd Degree",      isFelony = true, minTime = 1, maxTime = 45, minFine = 0, maxFine = 6000, description = "Theft of government property OR Any series of related thefts that result in a combined value of $50,000 or more from any one entity or person"},
    ["F203"] = {title = "Bribery",                  isFelony = true, minTime = 1, maxTime = 45, minFine = 0, maxFine = 6000, description = "Intentional giving, receiving, soliciting, offer or acceptance of any benefit, not necessarily of monetary value, in return for favorable action upon the accused by any peace officer or government official. A completed transaction is not necessary for a conviction, a simple acceptance or agreement of the benefit for favor is sufficient."},
    ["F204"] = {title = "Sale of Marijuana, 85u",   isFelony = true, minTime = 1, maxTime = 45, minFine = 0, maxFine = 6000, description = "Illegally possessing, harboring, distributing or transporting of Marijuana of 3.01oz (85 units) or more"},
    ["F205"] = {title = "Sale of Narcotics, 50u",   isFelony = true, minTime = 1, maxTime = 45, minFine = 0, maxFine = 6000, description = "Illegally possessing, harboring, distributing or transporting of any Schedule 1 narcotic equal or in excess of 50 units"},
    ["F206"] = {title = "Escape Custody",           isFelony = true, minTime = 1, maxTime = 45, minFine = 0, maxFine = 6000, description = "Escaping or assisting a person to escape custody wherein the person escape is already in the custody of law enforcement personnel."},
    ["F207"] = {title = "Felony Hit & Run",         isFelony = true, minTime = 1, maxTime = 45, minFine = 0, maxFine = 6000, description = "Regardless of collision fault determination, any person involved in the collision who fails to remain at the scene of a vehicular collision until released by first responders which results in great bodily injury or death to any person"},

    ["F301"] = {title = "Arson",                    isFelony = true, minTime = 1, maxTime = 30, minFine = 0, maxFine = 5000, description = "Unlawful setting of a fire or causing of any explosion resulting in damage of another person's property"},
    ["F302"] = {title = "Launder, 3rd Degree",      isFelony = true, minTime = 1, maxTime = 30, minFine = 0, maxFine = 5000, description = "Concealing, disguising or processing unlawfully obtained property of monetary value resulting in proceeds of $5,000 or more from any series of related events"},
    ["F303"] = {title = "Criminal Mischief",        isFelony = true, minTime = 1, maxTime = 30, minFine = 0, maxFine = 5000, description = "Intentional damage or negligent damage of, or destruction of, another person's property resulting in the loss of $5,000 or more through a single event"},
    ["F304"] = {title = "Larceny, 3rd Degree",      isFelony = true, minTime = 1, maxTime = 30, minFine = 0, maxFine = 5000, description = "Any single occurrence of theft wherein the item of monetary value is valued at or greater than $1,000 from any single entity or person"},
    ["F305"] = {title = "Unauthorized Access",      isFelony = true, minTime = 1, maxTime = 30, minFine = 0, maxFine = 5000, description = "Any person who accesses government or law enforcement informational systems without authorization OR Any person with authorization who accesses government or law enforcement informational systems for the purposes of committing any crime or for personal benefit"},
    ["F306"] = {title = "Witness Tampering",        isFelony = true, minTime = 1, maxTime = 30, minFine = 0, maxFine = 5000, description = "Persuading or coercing a witness, or prospective witness, in an official proceeding or court case to otherwise not participate in the proceeding OR the acceptance of any benefit as a witness, or prospective witness, for the actual or potential participation in proceedings"},
    ["F307"] = {title = "Evidence Tampering",       isFelony = true, minTime = 1, maxTime = 30, minFine = 0, maxFine = 5000, description = "Alteration, creation, destruction, concealment, transportation or placement of any real property for the purpose of impeding an official investigation or court proceeding prior to the acquittal or conviction of any criminal or civil proceeding."},
    ["F308"] = {title = "Impersonating an Official",isFelony = true, minTime = 1, maxTime = 30, minFine = 0, maxFine = 5000, description = "Any person who falsely presents oneself as, or acting in the capacity of, any public servant, government official, attorney, firefighter, healthcare provider or law enforcement officer. The maximum penalty shall apply anytime the person's false presentation results in great bodily harm or injury."},
    ["F309"] = {title = "Forgery",                  isFelony = true, minTime = 1, maxTime = 30, minFine = 0, maxFine = 5000, description = "Any person who results in the creation of a false documen OR causes the unauthorized alteration of a legitimate document. The maximum penalty shall apply in all cases where foregery was committed with the intent to deceive or defraud any entity or person."},
    ["F310"] = {title = "Firearm Smuggling",        isFelony = true, minTime = 1, maxTime = 30, minFine = 0, maxFine = 5000, description = "Any person who transports any firearm with the intent to sell or distribute the firearm OR possesses or transports any firearm with the purpose of avoiding legal restrictions"},
    ["F311"] = {title = "Sale of Marijuana, 71u",   isFelony = true, minTime = 1, maxTime = 30, minFine = 0, maxFine = 5000, description = "Illegally possessing, harboring, distributing or transporting of Marijuana of 2.51oz (71 units) or more"},
    ["F312"] = {title = "Sale of Narcotics, 6u",    isFelony = true, minTime = 1, maxTime = 30, minFine = 0, maxFine = 5000, description = "Illegally possessing, harboring, distributing or transporting of any Schedule 1 narcotic equal or in excess of 6 units"},
    ["F313"] = {title = "Possess Explosive",        isFelony = true, minTime = 1, maxTime = 30, minFine = 0, maxFine = 5000, description = "Any person who possesses; Any projectile containing explosive or inendiary material, including tracer ammunition OR any bomb, grenade, explosive missile or similar device used for causing an explosion or a fire OR any device capable of firing an explosive ordinance. This section does not apply to firefighter personnel, law enforcement officers or military officials during the course of their duties."},
    ["F314"] = {title = "False Imprisonment",       isFelony = true, minTime = 1, maxTime = 30, minFine = 0, maxFine = 5000, description = "Any person who causes another person to be confined or unable to leave against the confined persons will without being transported to another location. The maximum penalty applies in all cases of great bodily injury or harm that results to any person due to the false imprisonment."},
    ["F315"] = {title = "Possess Dangerous Weapon", isFelony = true, minTime = 1, maxTime = 30, minFine = 0, maxFine = 5000, description = "Any person who possesses a dangerous weapon or Class 3 weapon without authorization by a Chief law enforcement officer or judge. This section shall not apply to any person who was unknowingly in possession of the weapon or to any government official, law enforcement officer or military personnel where the possession of the weapon is necessary in the line of duty"},

    -- Misdemeanor Offenses
    ["M101"] = {title = "Assault",                  minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Intentionally, knowingly or recklessly causing harm or bodily injury to another OR causing contact with another person and should reasonably know that the other will regard such contact as offensive or provocative."},
    ["M102"] = {title = "Resisting Detention",      minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Preventing or obstructing a law enforcement officer from arresting, searching or detaining an individual after being informed of a lawful arrest, search or detention"},
    ["M103"] = {title = "Evading Arrest",           minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Fleeing or attempting to flee a law enforcement officer who is attempting to lawfully arrest or detain said person"},
    ["M104"] = {title = "Abuse of Authority",       minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Misuse of government property, personnel or services by a member of public office with intent to defraud or harm another for personal or professional gain"},
    ["M105"] = {title = "Official Oppression",      minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Subjection of a person to mistreatment, arrest, search, seizure or universal declaration of human rights violation by a public official"},
    ["M106"] = {title = "False Report",             minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Communicating in any manner a report of an emergency or crime that the person knows to be false"},
    ["M107"] = {title = "Interference with 911",    minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Intentional obstruction or prevention of another from lawfully utilizing the emergency system"},
    ["M108"] = {title = "Terroristic Threats",      minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Threatening violence to any person, organization or property with the intent to, provoke reaction by impact or interrupt emergency services or law enforcement"},
    ["M109"] = {title = "Tamper Government Vehicle",minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Intentionally tampering, operating or entering a government or law enforcement vehicle, including but not limited to operating, activating or deactivating any operational vehicle component"},
    ["M110"] = {title = "Grand Theft Auto",         minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Entering or possessing a vehicle of any type without the express consent of the owner"},
    ["M111"] = {title = "Launder, 4th Degree",      minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Concealing, disguising or processing unlawfully obtained property of monetary value resulting in proceeds of $1,000 or more from any series of related events"},
    ["M112"] = {title = "Mischief, 2nd Degree",     minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Damage or Destruction resulting in loss of $50,000 or more OR damage or Destruction of government property"},
    ["M113"] = {title = "Sale of Marijuana, 57u",   minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Illegally possessing, harboring, distributing or transporting of Marijuana of 1.01oz (57 units) or more"},
    ["M114"] = {title = "Sale of Narcotics, 1u",    minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Illegally possessing, harboring, distributing or transporting of any Schedule 1 narcotic equal or in excess of 1 unit"},
    ["M115"] = {title = "Mischief, 3rd Degree",     minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Damage or Destruction of another's property resulting in loss valued at $1,000 or more"},
    ["M116"] = {title = "Contempt of Court",        minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Any person who commits any disorderly, contemptuous or insolent behavior during the sitting court of justice, in the immediate view and presence of the court or knowingly defying any unexpired court order"},
    ["M117"] = {title = "Possess Stolen Property",  minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Any person in possession of the property or identification card of any person in which they are not the owner or the subject of receipt"},
    ["M118"] = {title = "Recklessly Handle Firearm",minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Any person who recklessly handles a firearm or taser as to endanger the safety of another person, whether the firearm is loaded or unloaded, or any person who handles or possesses a firearm while impaired by alcohol or mental state affecting substances or narcotics"},
    ["M119"] = {title = "Carry Loaded Firearm",     minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Carrying an unconcealed and loaded firearm on your person within 500 feet of any public property, school, or private property where firearm possession is prohibited unless the person is carrying the firearm unloaded in a locked container"},
    ["M120"] = {title = "Unlawful Possession",      minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Any convicted felon, person convicted of domestic violence, any crime involving a weapon, or any person who is on parole or probation, who possesses any firearm or magazine OR any person who possesses a firearm without a weapons license unless that person is in possession of a weapon typically used for hunting and is engaged in hunting or going directly to or from a hunting activity"},
    ["M121"] = {title = "Violate Parole/Probation", minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Violating any condition as a part of bail or early release set by the court, OR arrest for a criminal offense of Class B Misdemeanors or above while on probation or parole, OR failure to appear to any court date"},
    ["M122"] = {title = "Possess Burglary Tools",   minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Any person who possesses, created, modifies or otherwise causes to be created or modified any weapon, tool or item commonly used for burglary, safecracking or other crime of larceny under circumstances evincing an intent to use or allow to be used the item for the purposes of larceny. Simple possession of burglary tools by mechanics or others used for lawful purposes is not a violation of this section"},
    ["M123"] = {title = "Unlicensed Armed security",minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Any person who operates or portrays themselves as an armed security officer, whether private or public, without a license."},
    ["M124"] = {title = "Misrepresent Vehicle Tag", minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Any person who removes, modified, damages or otherwise alters any vehicle license plate or vehicle identification number without approval by the Department of Motor Vehicles or the San Andreas Highway Patrol, with the intent to conceal or misrepesent the identity of the vehicle the identification is affixed to."},
    ["M125"] = {title = "Strongarm Robbery",        minTime = 1, maxTime = 20, minFine = 0, maxFine = 3000, description = "Commits a theft by means of force or fear without the use of a weapon"},

    ["M201"] = {title = "Criminal Trespass",        minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Entering or remaining at any private or public location without the express consent of the lawful owner or primary occupant whereas the person has either been advised or should have reasonably known they should not have entered or remained"},
    ["M202"] = {title = "Hit and Run",              minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Failure to stop and remain at the scene of an accident in which damages of $300 or more occurred OR any person suffers an injury as a result of the failure to stop"},
    ["M203"] = {title = "Indecent Exposure",        minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Any person who exposes their genitalia, buttocks, breasts or undergarments other than garments typically used as a bathing suit in a public location or outside of a person's residence. Any place of business whereas the exposure is a condition of the person's employment must advertise or place on notice the exposure of such and must not be viewable from a public area"},
    ["M204"] = {title = "Money Laundering",         minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Concealing, disguising or processing unlawfully obtained property of monetary value resulting in proceeds of $5,000 or more from any series of related events"},
    ["M205"] = {title = "Mischief, 4th Degree",     minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Damage or Destruction resulting in loss of $50,000 or more OR damage or Destruction of government property"},
    ["M206"] = {title = "Larceny, 4th Degree",      minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Any single occurrence of theft wherein the item of monetary value is valued at or greater than $1,000 from any single entity or person"},
    ["M207"] = {title = "Deceptive Business",       minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Misrepresenting any aspect of a business, it's practices, or conduct to receive any benefit, financial or otherwise"},
    ["M208"] = {title = "Fail to Identify",         minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Refusing to provide truthful identification or personal information upon request by a law enforcement officer in the course of an arrest or detention"},
    ["M209"] = {title = "Interfere Duty",           minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Interrupts, impedes, disturbs, prevents or otherwise interferes with a public servant or law enforcement official from discharging their lawful and legal duties"},
    ["M210"] = {title = "Harassment",               minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Intentional embarrassment, annoyance or abuse of a person made via a comment, suggestion, request or otherwise means of verbal or written means, when the person has clearly communicated the effects of such"},
    ["M211"] = {title = "Driving Under Influence",  minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Any person who operates any vehicle, aircraft or watercraft while intoxicated or under the influence of alcohol, controlled substance or any other substance that impairs the ability to operate a vehicle, aircraft or watercraft in a safe and responsible manner. All persons above 0.08 BAC are guilty regardless of their proficiency of operation."},
    ["M212"] = {title = "Obstruct Passage",         minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Obstructing any public highway, garage, alleyway, entrance or exit without legal authority with the intent to prevent, obstruct or hinder the free movement of any person"},
    ["M213"] = {title = "Sale of Marijuana, 43u",   minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Illegally possessing, harboring, distributing or transporting of Marijuana of 2.51oz (71 units) or more"},
    ["M214"] = {title = "Sale of Narcotics, 1u S2", minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Illegally possessing, harboring, distributing or transporting of any Schedule 1 narcotic equal or in excess of 6 units"},
    ["M215"] = {title = "Reckless Driving",         minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Operating a vehicle, aircraft, vessel or watercraft with willful OR intentional disregard for the safety of others or property"},
    ["M216"] = {title = "Street Racing",            minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Racing any other vehicle, aircraft or watercraft on a public highway, waterway or air vector unless the race is a publicly sanctioned event on a closed course"},
    ["M217"] = {title = "Repeat Moving Offenses",   minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Operating a vehicle in a reckless or irresponsible manner while disregarding traffic control devices or traffic laws AND has at least five prior moving violations. For the purposes of this section, prior shall mean convicted before the occurrence of this event"},
    ["M218"] = {title = "Hit and Run",              minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Leaving the scene or failing to render aid at the scene of a collision wherein the person leaving the scene is involved in or causes the collision either directly or indirectly when landscaping, signs, lights or other property are damaged"},
    ["M219"] = {title = "Failure to Comply",        minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Any person willfully failing or refusing to comply with the lawful order or direction of any law enforcement officer"},
    ["M220"] = {title = "Obstruct Official",        minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Any person who fillfully obstructs, hinders or prevents the lawful execution of any legal process or lawful apprehension of any person OR obstructs, resists or interferes with a law enforcement officer while in the performance of official duties OR obstructures, hinders or interferes with a public servant, firefighter, paramedic, or emergency medical technician in the performance of official duties"},
    ["M221"] = {title = "Minor in Possession",      minTime = 1, maxTime = 15, minFine = 0, maxFine = 2000, description = "Any person under the age of 21 who possesses or consumes alcohol, marijuana or tobacco OR causes or provides any person under the age of 21 to consume alcohol, marijuana or tobacco"},

    ["M301"] = {title = "Criminal Threats",         minTime = 1, maxTime = 10, minFine = 0, maxFine = 1000, description = "Any person who threatens another person with injury or unlawful contact"},
    ["M302"] = {title = "Possess Paraphernalia",    minTime = 1, maxTime = 10, minFine = 0, maxFine = 1000, description = "Any person who possesses materials used primarily for the production or consumption of drugs such as a pipe, spoon, or baggie"},
    ["M303"] = {title = "Criminal Mischief",        minTime = 1, maxTime = 10, minFine = 0, maxFine = 1000, description = "Any person who damages or destroys the property of another person resulting in a valued loss of less than $100 or causes consequential incovenience to any other person"},
    ["M304"] = {title = "False Statements",         minTime = 1, maxTime = 10, minFine = 0, maxFine = 1000, description = "Providing or communicating statements to law enforcement that the person knows to be false or misleading"},
    ["M305"] = {title = "Disorderly Conduct",       minTime = 1, maxTime = 10, minFine = 0, maxFine = 1000, description = "Any person who unlawfully engages in mutual combat, fighting or violent acts against another person, OR in any public place: causes unreasonable noise OR uses abusive or obscene language OR makes any obscene gesture OR without lawful authority disturbs any lawful assembly or meeting of persons OR obstructs vehicular or pedestrian traffic OR congregates with others in a public place and ignores a lawful order to disperse OR creates a hazardous or physically offensive condition by any act with serves no legitimate purpose"},
    ["M306"] = {title = "Petit Larceny",            minTime = 1, maxTime = 10, minFine = 0, maxFine = 1000, description = "Unlawful deprivation or theft of property values less than $250 from the legal owner"},
    ["M307"] = {title = "Sale of Marijuana, 29u",   minTime = 1, maxTime = 10, minFine = 0, maxFine = 1000, description = "Illegally possessing, harboring, distributing or transporting of Marijuana of 2.51oz (71 units) or more"},
    ["M308"] = {title = "Sale of Narcotics, 1u S3", minTime = 1, maxTime = 10, minFine = 0, maxFine = 1000, description = "Illegally possessing, harboring, distributing or transporting of any Schedule 1 narcotic equal or in excess of 6 units"},
    ["M309"] = {title = "Drive Without License",    minTime = 1, maxTime = 10, minFine = 0, maxFine = 1000, description = "Operating a vehicle, aircraft, vessel or watercraft with willful OR intentional disregard for the safety of others or property"},
    ["M310"] = {title = "Misuse of 911",            minTime = 1, maxTime = 10, minFine = 0, maxFine = 1000, description = "Any person who requests emergency services where no actual emergency exists and the caller does not have good faith that emergency assistance is necessary"},
    ["M311"] = {title = "Failure to Pay Fine",      minTime = 1, maxTime = 10, minFine = 0, maxFine = 1000, description = "Failure to pay any fine, bill or invoice within 14 days of issurance wherein the fine was issued by a public agency as a consequence or legal proceeding"},
    ["M312"] = {title = "Failure to Appear",        minTime = 1, maxTime = 10, minFine = 0, maxFine = 1000, description = "Any person who does not appear to the designated court at the time the summons is returnable"},
    ["M313"] = {title = "Unlicensed Unarm Security",minTime = 1, maxTime = 10, minFine = 0, maxFine = 1000, description = "Any person who operates or portrays themselves to be a security officer for any company or business without a license"},

    ["M401"] = {title = "Public Intoxication",      minTime = 1, maxTime = 5, minFine = 0, maxFine = 500, description = "Any person under the influence of any substance to a degree that the person presents a danger to themselves or others in a public location"},
    ["M402"] = {title = "Urinating in Public",      minTime = 1, maxTime = 5, minFine = 0, maxFine = 500, description = "Urinating or defecating in a public place outside of a location designated as a bathroom, while in the area of any incorporated city or near any public highway"},
    ["M403"] = {title = "Open Alcohol Container",   minTime = 1, maxTime = 5, minFine = 0, maxFine = 500, description = "Any person who possesses or consumes alcohol from any container that is not sealed by the manufacturer while in a public location or within a motor vehicle"},
    ["M404"] = {title = "Littering",                minTime = 1, maxTime = 5, minFine = 0, maxFine = 500, description = "Depositing solid waste in any public area outside of proper waste receptacles"},
    ["M405"] = {title = "Noise Violation",          minTime = 1, maxTime = 5, minFine = 0, maxFine = 500, description = "Creating any unnecessary or unreasonable noise or sound intended to annoy, disturb or otherwise endangers the comfort and peace of others"},

    ["CO101"] = {title = "Facilitate Criminal Act", minTime = 1, maxTime = 5, minFine = 0, maxFine = 1000, description = "Any business owner who allows the use of any portion of their business or businesses property for the purposes of criminal activity"},

    -- Infractions (Fine Only)+

    ["VT101"] = {title = "General Speed Law",       minTime = 1, maxTime = 12, minFine = 0, maxFine =  500, description = "Any person who drives a vehicle too fast for current road conditions"},
    ["VT102"] = {title = "Speed in Excess of 5",    minTime = 1, maxTime = 12, minFine = 0, maxFine =  500, description = "Any person who exceeds the posted or common speed limit by 5 miles per hour, or greater"},
    ["VT103"] = {title = "Speed in Excess of 10",   minTime = 1, maxTime = 12, minFine = 0, maxFine =  750, description = "Any person who exceeds the posted or common speed limit by 10 miles per hour, or greater"},
    ["VT104"] = {title = "Speed in Excess of 20",   minTime = 1, maxTime = 12, minFine = 0, maxFine = 1000, description = "Any person who exceeds the posted or common speed limit by 20 miles per hour, or greater"},
    ["VT105"] = {title = "Speed in Excess of 30",   minTime = 1, maxTime = 12, minFine = 0, maxFine = 1250, description = "Any person who exceeds the posted or common speed limit by 30 miles per hour, or greater"},
    ["VT106"] = {title = "Move Over Law",           minTime = 1, maxTime = 12, minFine = 0, maxFine = 1000, description = "On any road with two or more lanes for one direction of travel, fails to move out of the lane or reduce speed within the lane immediately adjacent to any stopped emergency vehicles with emergency lights activated. For the purposes of this section, an emergency vehicle is any vehicle used for medical care, firefighting, law enforcement, maintenance, construction or towing."},
    ["VT107"] = {title = "Drive Without Lights",    minTime = 1, maxTime = 12, minFine = 0, maxFine =  500, description = "Driving or operating a vehicle without utilization of the exterior lighting equipment provided by the manufacturer during times of low visibility"},
    ["VT108"] = {title = "Traffic Device Violation",minTime = 1, maxTime = 12, minFine = 0, maxFine = 1250, description = "Any person who disregards any traffic control device"},
    ["VT109"] = {title = "Stop Sign Violation",     minTime = 1, maxTime = 12, minFine = 0, maxFine = 1000, description = "Any person who does not come to a complete stop at any stop sign"},
    ["VT110"] = {title = "Fail Maintain lane",      minTime = 1, maxTime = 12, minFine = 0, maxFine = 1000, description = "Any person who operates or causes any vehicle to be operated outside of the plane of the center marker or outer edge of the roadway"},
    ["VT111"] = {title = "No Passing Zone",         minTime = 1, maxTime = 12, minFine = 0, maxFine =  750, description = "Passing any other vehicle or pedestrian in any zone designated as a No Passing area, such as a no passing sign or solid lines painted upon the roadway"},
    ["VT112"] = {title = "Right of Way Violation",  minTime = 1, maxTime = 12, minFine = 0, maxFine =  750, description = "Any person who fails to yield to the vehicle on the right at an uncontrolled intersection, OR fails to yield to a pedestrian at an intersection or crosswalk OR while traveling on an unpaved or private roadway fails to yield to a vehicle on a paved roadway"},
    ["VT113"] = {title = "Failure to Yield",        minTime = 1, maxTime = 12, minFine = 0, maxFine = 1000, description = "Any person who fails to surrender the right of way to any emergency vehicle that has it's lights activated and is sounding a siren"},
    ["VT114"] = {title = "No Parking Zone",         minTime = 1, maxTime = 12, minFine = 0, maxFine =  500, description = "Any person who parks or causes any vehicle to be parked in any location where parking is unauthorized or not permitted by posted signs, red-painted curbs, active construction or repair is occurring or within 100 feet of any intersection or fire hydrant"},
    ["VT115"] = {title = "Illegal Window Tint",     minTime = 1, maxTime = 12, minFine = 0, maxFine =  500, description = "Any person operating a vehicle with window tint or shading that causes near obscuration of the interior of the vehicle from any window when the window is in the closed position"},
    ["VT116"] = {title = "Visible Underglow",       minTime = 1, maxTime = 12, minFine = 0, maxFine =  500, description = "Any person who operates a vehicle with red or blue underglow OR any headlights that are not white or xenon"},
    ["VT117"] = {title = "Unroadworthy",            minTime = 1, maxTime = 12, minFine = 0, maxFine =  500, description = "Any vehicle that is damaged or unroadworthy; A vehicle that is unsafe to operate on a public highway"},
    ["VT118"] = {title = "Exhibition Driving",      minTime = 1, maxTime = 12, minFine = 0, maxFine = 1250, description = "Any person who drives a vehicle on a highway, alley, public park, recreational area or public property that creates or causes unnecessary engine noise, tire squeal, skid or slide on acceleration or stopping OR that simulates a temporary race OR causes the vehicle to unnecessarily turn abruptly or swap"},
    ["VT119"] = {title = "Improper U-Turn",         minTime = 1, maxTime = 12, minFine = 0, maxFine =  750, description = "Any vehicle being turned to proceed in the opposite direction wherein the manuevering vehicle cannot be seen by the driver of any other vehicle approaching from 1000 feet. A driver may utilize the furthest lane and the shoulder temporarily to complete a u-turn on any roadway with two or more lanes in the same direction"},
    ["VT120"] = {title = "Using Cellular Device",   minTime = 1, maxTime = 12, minFine = 0, maxFine = 1250, description = "Operating a vehicle on any public roadway while using a cellular phone"},
    ["VT121"] = {title = "Commercial Violation",    minTime = 1, maxTime = 12, minFine = 0, maxFine = 2000, description = "Any traffic violations committed at any time while driving a Commercial Vehicle"},

    -- Special laws (fish and game, etc)

    ["FG101"] = {title = "Illegal Bait",            minTime = 1, maxTime = 12, minFine = 0, maxFine = 1500, revoke = 'hunting',  description = "Taking or possessing a turtle for use as a bait for fishing"},
    ["FG102"] = {title = "Illegal Taking",          minTime = 1, maxTime = 12, minFine = 0, maxFine = 1500, revoke = 'hunting',  description = "The taking or possession of spike buck or spotted fawn OR allowing someone else to tag an animal you have killed OR assisting someone kill animals that you are not licensed to hunt"},
    ["FG103"] = {title = "Out of Season",           minTime = 1, maxTime = 12, minFine = 0, maxFine =  150, revoke = 'hunting',  description = "Any person who takes a mammal, bird, fish, reptile or amphibian outside of the established season OR possesses during the established season any bag limit or possession limit established by the commission"},
    ["FG104"] = {title = "Unpermitted Event",       minTime = 1, maxTime = 12, minFine = 0, maxFine =  500,                      description = "Any person who offers or participates in any prize or reward for taking of game in any contest, tournament or derby without sanction of the commission"},
    ["FG105"] = {title = "Loaded Firearm Vehicle",  minTime = 1, maxTime = 12, minFine = 0, maxFine = 2500, revoke = 'hunting',  description = "Any person who causes to be carried in their possession a rifle or shotgun typically used for hunting activities within a motor vehicle driven on or along any public highway or pathway open to the public unless the weapon is stored in the trunk or locked container OR carries a weapon consistent with weapons used for hunting activities in possession of greater than 50 rounds of ammunition"},
    ["FG106"] = {title = "Unlicensed Hunting",      minTime = 1, maxTime = 12, minFine = 0, maxFine =  750,                      description = "Any person who engages in hunting or assists another in engaging in hunting without having a hunting license"},
    ["FG107"] = {title = "Unauthorized Hunting",    minTime = 1, maxTime = 12, minFine = 0, maxFine = 1000, revoke = 'hunting',  description = "Any person who crosses any fence, gate or otherwise enters land for the purpose of hunting activities without the express consent of the owner of the land, the owner's agency or the person in lawful possession of the land"},
    ["FG108"] = {title = "Shooting from Vehicle",   minTime = 1, maxTime = 12, minFine = 0, maxFine = 5000, revoke = 'hunting',  description = "Any person who discharges a firearm from inside or upon a vehicle"},
    ["FG109"] = {title = "Unlawful Firearm",        minTime = 1, maxTime = 12, minFine = 0, maxFine = 5000, revoke = 'hunting',  description = "Any person who engages in hunting with any firearm capable of automatic fire"},
    ["FG110"] = {title = "Hunting at Night",        minTime = 1, maxTime = 12, minFine = 0, maxFine =  250,                      description = "Any person engaged in hunting between 30 minutes after dusk and 30 minutes before dawn"},
    ["FG111"] = {title = "Failure to Notify",       minTime = 1, maxTime = 12, minFine = 0, maxFine =  100, revoke = 'hunting',  description = "Any person who fails to notify a game warden of the initiation of any hunting activity"},
    ["FG112"] = {title = "Shoot near Roadway",      minTime = 1, maxTime = 12, minFine = 0, maxFine = 5000, revoke = 'hunting',  description = "Any person who discharges a firearm within 150 feet of any public pathway OR discharges a firearm where the projectile travels across any public pathway"},
    ["FG113"] = {title = "Use of a Crossbow",       minTime = 1, maxTime = 12, minFine = 0, maxFine =  500, revoke = 'hunting',  description = "Any person who uses a crossbow while engaged in hunting activities without express authorization from the commission"},
    ["FG114"] = {title = "Hunting under Influence", minTime = 1, maxTime = 12, minFine = 0, maxFine = 2500, revoke = 'hunting',  description = "Any person who engages in hunting activities while under the influence of any substance"},

}