RACE_STATUS_STARTING = 0
RACE_STATUS_RACING = 1
RACE_STATUS_FINISHED = 2

PLAYER_STATE_IDLE = 0
PLAYER_STATE_JOINED = 1
PLAYER_STATE_RACING = 2
PLAYER_STATE_FINISHED = 3
PLAYER_STATE_EXITED = 4

RACE_CHECKPOINT_TYPE = 18
RACE_CHECKPOINT_FINISH_TYPE = 21