local QBCore = exports['qb-core']:GetCoreObject()

function getPlayerIdentifier(playerId)
    local Player = QBCore.Functions.GetPlayer(playerId)
    return Player.PlayerData.citizenid
end

function getPlayerMoney(playerId)
    local Player = QBCore.Functions.GetPlayer(playerId)
    return Player.PlayerData.money.cash
end

function removePlayerMoney(playerId, amount)
    local Player = QBCore.Functions.GetPlayer(playerId)
    Player.Functions.RemoveMoney('cash', amount)
end

function givePlayerMoney(playerId, amount)
    local Player = QBCore.Functions.GetPlayer(playerId)
    Player.Functions.AddMoney('cash', amount)
end

-- SERVER export - This function is exported, so it can be opened from any other server-side script by using 'exports['rahe-racing']:openRacingTablet(source)'
function openRacingTablet(playerId)
    TriggerClientEvent('rahe-racing:client:openTablet', playerId)
end

function notifyPlayer(playerId, message)
    TriggerClientEvent('chatMessage', playerId, "SERVER", "normal", message)
end

-- You can use the function provided here, or use your own existing logic
function getVehicleClassFromHash(modelHash)
    return getVehicleClassFromHash(modelHash)
end

function getVehicleClassFromHash(modelHash)
    for _, v in ipairs(supportedVehicles) do
        if GetHashKey(v.model) == modelHash then
            return v.class
        end
    end

    -- Returns 'C' class for a vehicle when a class wasn't found for it
    return 'C'
end

-- Feel free to add your own vehicles here. Most of the default cars are here, modded cars have to be added!
supportedVehicles = {
    { name = "Asbo", model = "asbo", class = "D" },
    { name = "blista", model = "blista", class = "D" },
    { name = "club", model = "club", class = "D" },
    { name = "dilettante", model = "dilettante", class = "D" },
    { name = "issi2", model = "issi2", class = "D" },
    { name = "issi3", model = "issi3", class = "D" },
    { name = "panto", model = "panto", class = "D" },
    { name = "rhapsody", model = "rhapsody", class = "D" },
    { name = "brioso2", model = "brioso2", class = "D" },
    { name = "felon", model = "felon", class = "D" },
    { name = "blade", model = "blade", class = "D" },
    { name = "buccaneer", model = "buccaneer", class = "D" },
    { name = "buccaneer2", model = "buccaneer2", class = "D" },
    { name = "chino", model = "chino", class = "D" },
    { name = "chino2", model = "chino2", class = "D" },
    { name = "clique", model = "clique", class = "D" },
    { name = "faction", model = "faction", class = "D" },
    { name = "faction2", model = "faction2", class = "D" },
    { name = "faction3", model = "faction3", class = "D" },
    { name = "ellie", model = "ellie", class = "D" },
    { name = "hermes", model = "hermes", class = "D" },
    { name = "lurcher", model = "lurcher", class = "D" },
    { name = "moonbeam", model = "moonbeam", class = "D" },
    { name = "moonbeam2", model = "moonbeam2", class = "D" },
    { name = "peyote2", model = "peyote2", class = "D" },
    { name = "phoenix", model = "phoenix", class = "D" },
    { name = "picador", model = "picador", class = "D" },
    { name = "ratloader2", model = "ratloader2", class = "D" },
    { name = "sabregt", model = "sabregt", class = "D" },
    { name = "sabregt2", model = "sabregt2", class = "D" },
    { name = "slamvan", model = "slamvan", class = "D" },
    { name = "slamvan2", model = "slamvan2", class = "D" },
    { name = "slamvan3", model = "slamvan3", class = "D" },
    { name = "stalion", model = "stalion", class = "D" },
    { name = "stalion2", model = "stalion2", class = "D" },
    { name = "tampa", model = "tampa", class = "D" },
    { name = "vamos", model = "vamos", class = "D" },
    { name = "vigero", model = "vigero", class = "D" },
    { name = "virgo", model = "virgo", class = "D" },
    { name = "virgo2", model = "virgo2", class = "D" },
    { name = "virgo3", model = "virgo3", class = "D" },
    { name = "voodoo", model = "voodoo", class = "D" },
    { name = "yosemite", model = "yosemite", class = "D" },
    { name = "bfinjection", model = "bfinjection", class = "D" },
    { name = "bifta", model = "bifta", class = "D" },
    { name = "blazer", model = "blazer", class = "D" },
    { name = "blazer2", model = "blazer2", class = "D" },
    { name = "blazer3", model = "blazer3", class = "D" },
    { name = "blazer4", model = "blazer4", class = "D" },
    { name = "dune", model = "dune", class = "D" },
    { name = "everon", model = "everon", class = "D" },
    { name = "freecrawler", model = "freecrawler", class = "D" },
    { name = "kalahari", model = "kalahari", class = "D" },
    { name = "kamacho", model = "kamacho", class = "D" },
    { name = "outlaw", model = "outlaw", class = "D" },
    { name = "rancherxl", model = "rancherxl", class = "D" },
    { name = "rebel2", model = "rebel2", class = "D" },
    { name = "riata", model = "riata", class = "D" },
    { name = "sandking", model = "sandking", class = "D" },
    { name = "sandking2", model = "sandking2", class = "D" },
    { name = "verus", model = "verus", class = "D" },
    { name = "winky", model = "winky", class = "D" },
    { name = "baller", model = "baller", class = "D" },
    { name = "baller2", model = "baller2", class = "D" },
    { name = "baller3", model = "baller3", class = "D" },
    { name = "baller4", model = "baller4", class = "D" },
    { name = "dubsta", model = "dubsta", class = "D" },
    { name = "dubsta2", model = "dubsta2", class = "D" },
    { name = "fq2", model = "fq2", class = "D" },
    { name = "granger", model = "granger", class = "D" },
    { name = "gresley", model = "gresley", class = "D" },
    { name = "huntley", model = "huntley", class = "D" },
    { name = "landstalker", model = "landstalker", class = "D" },
    { name = "landstalker2", model = "landstalker2", class = "D" },
    { name = "mesa", model = "mesa", class = "D" },
    { name = "radi", model = "radi", class = "D" },
    { name = "rebla", model = "rebla", class = "D" },
    { name = "rocoto", model = "rocoto", class = "D" },
    { name = "seminole", model = "seminole", class = "D" },
    { name = "seminole2", model = "seminole2", class = "D" },
    { name = "serrano", model = "serrano", class = "D" },
    { name = "asea", model = "asea", class = "D" },
    { name = "asterope", model = "asterope", class = "D" },
    { name = "emperor", model = "emperor", class = "D" },
    { name = "fugitive", model = "fugitive", class = "D" },
    { name = "glendale", model = "glendale", class = "D" },
    { name = "glendale2", model = "glendale2", class = "D" },
    { name = "ingot", model = "ingot", class = "D" },
    { name = "intruder", model = "intruder", class = "D" },
    { name = "premier", model = "premier", class = "D" },
    { name = "primo", model = "primo", class = "D" },
    { name = "primo2", model = "primo2", class = "D" },
    { name = "regina", model = "regina", class = "D" },
    { name = "stafford", model = "stafford", class = "D" },
    { name = "stanier", model = "stanier", class = "D" },
    { name = "stratum", model = "stratum", class = "D" },
    { name = "stretch", model = "stretch", class = "D" },
    { name = "surge", model = "surge", class = "D" },
    { name = "warrener", model = "warrener", class = "D" },
    { name = "washington", model = "washington", class = "D" },
    { name = "patriot3", model = "patriot3", class = "D" },
    { name = "blista2", model = "blista2", class = "D" },
    { name = "blista3", model = "blista3", class = "D" },
    { name = "buffalo", model = "buffalo", class = "D" },
    { name = "futo", model = "futo", class = "D" },
    { name = "schafter2", model = "schafter2", class = "D" },
    { name = "tropos", model = "tropos", class = "D" },
    { name = "remus", model = "remus", class = "D" },
    { name = "ardent", model = "ardent", class = "D" },
    { name = "btype", model = "btype", class = "D" },
    { name = "btype2", model = "btype2", class = "D" },
    { name = "btype3", model = "btype3", class = "D" },
    { name = "dynasty", model = "dynasty", class = "D" },
    { name = "fagaloa", model = "fagaloa", class = "D" },
    { name = "manana", model = "manana", class = "D" },
    { name = "manana2", model = "manana2", class = "D" },
    { name = "michelli", model = "michelli", class = "D" },
    { name = "peyote", model = "peyote", class = "D" },
    { name = "peyote3", model = "peyote3", class = "D" },
    { name = "pigalle", model = "pigalle", class = "D" },
    { name = "tornado", model = "tornado", class = "D" },
    { name = "tornado5", model = "tornado5", class = "D" },
    { name = "bison", model = "bison", class = "D" },
    { name = "bobcatxl", model = "bobcatxl", class = "D" },
    { name = "burrito3", model = "burrito3", class = "D" },
    { name = "gburrito2", model = "gburrito2", class = "D" },
    { name = "rumpo", model = "rumpo", class = "D" },
    { name = "journey", model = "journey", class = "D" },
    { name = "minivan", model = "minivan", class = "D" },
    { name = "minivan2", model = "minivan2", class = "D" },
    { name = "paradise", model = "paradise", class = "D" },
    { name = "rumpo3", model = "rumpo3", class = "D" },
    { name = "speedo", model = "speedo", class = "D" },
    { name = "speedo4", model = "speedo4", class = "D" },
    { name = "surfer", model = "surfer", class = "D" },
    { name = "youga3", model = "youga3", class = "D" },
    { name = "youga", model = "youga", class = "D" },
    { name = "youga2", model = "youga2", class = "D" },
    { name = "youga4", model = "youga4", class = "D" },
    { name = "mule5", model = "mule5", class = "D" },
    { name = "sadler", model = "sadler", class = "D" },
    { name = "guardian", model = "guardian", class = "D" },
    { name = "slamtruck", model = "slamtruck", class = "D" },
    { name = "warrener2", model = "warrener2", class = "D" },
    { name = "sharkdurango", model = "sharkdurango", class = "D" },
    { name = "vanz3rdgen", model = "vanz3rdgen", class = "D" },
    { name = "vanz20f350sema", model = "vanz20f350sema", class = "D" },
    { name = "vanzgmc4", model = "vanzgmc4", class = "D" },
    { name = "vanzferd", model = "vanzferd", class = "D" },
    { name = "cannedham", model = "cannedham", class = "D" },
    { name = "cannedhamdune", model = "cannedhamdune", class = "D" },
    { name = "cannedhammud", model = "cannedhammud", class = "D" },
    { name = "16charger", model = "16charger", class = "D" },
    { name = "18f350ds", model = "18f350ds", class = "D" },
    { name = "20denalihdg", model = "20denalihdg", class = "D" },
    { name = "20f250", model = "20f250", class = "D" },
    { name = "20trailboss", model = "20trailboss", class = "D" },
    { name = "193500hd", model = "193500hd", class = "D" },
    { name = "65c10", model = "65c10", class = "D" },
    { name = "92dodgeram", model = "92dodgeram", class = "D" },
    { name = "vanzjeep", model = "vanzjeep", class = "D" },
    { name = "bad250", model = "bad250", class = "D" },
    { name = "bcsierrahd", model = "bcsierrahd", class = "D" },
    { name = "bc06silv", model = "bc06silv", class = "D" },
    { name = "bc21bronco", model = "bc21bronco", class = "D" },
    { name = "bc80silv", model = "bc80silv", class = "D" },
    { name = "bc2500hd", model = "bc2500hd", class = "D" },
    { name = "bcal450", model = "bcal450", class = "D" },
    { name = "bcbanshee", model = "bcbanshee", class = "D" },
    { name = "bcbuggyxl", model = "bcbuggyxl", class = "D" },
    { name = "bcfabjeep", model = "bcfabjeep", class = "D" },
    { name = "crawler", model = "crawler", class = "D" },

    -------------------------c class--------------------------------
    { name = "brioso", model = "brioso", class = "C" },
    { name = "cogcabrio", model = "cogcabrio", class = "C" },
    { name = "exemplar", model = "exemplar", class = "C" },
    { name = "f620", model = "f620", class = "C" },
    { name = "felon2", model = "felon2", class = "C" },
    { name = "jackal", model = "jackal", class = "C" },
    { name = "felon", model = "felon", class = "C" },
    { name = "dominator", model = "dominator", class = "C" },
    { name = "dukes", model = "dukes", class = "C" },
    { name = "gauntlet", model = "gauntlet", class = "C" },
    { name = "gauntlet2", model = "gauntlet2", class = "C" },
    { name = "hotknife", model = "hotknife", class = "C" },
    { name = "hustler", model = "hustler", class = "C" },
    { name = "impaler", model = "impaler", class = "C" },
    { name = "imperator", model = "imperator", class = "C" },
    { name = "nightshade", model = "nightshade", class = "C" },
    { name = "ruiner", model = "ruiner", class = "C" },
    { name = "yosemite3", model = "yosemite3", class = "C" },
    { name = "brawler", model = "brawler", class = "C" },
    { name = "dubsta3", model = "dubsta3", class = "C" },
    { name = "hellion", model = "hellion", class = "C" },
    { name = "trophytruck", model = "trophytruck", class = "C" },
    { name = "trophytruck2", model = "trophytruck2", class = "C" },
    { name = "vagrant", model = "vagrant", class = "D" },
    { name = "contender", model = "contender", class = "C" },
    { name = "habanero", model = "habanero", class = "C" },
    { name = "novak", model = "novak", class = "C" },
    { name = "toros", model = "toros", class = "C" },
    { name = "xls", model = "xls", class = "C" },
    { name = "cog55", model = "cog55", class = "C" },
    { name = "cognoscenti", model = "cognoscenti", class = "C" },
    { name = "superd", model = "superd", class = "C" },
    { name = "tailgater", model = "tailgater", class = "C" },
    { name = "tailgater2", model = "tailgater2", class = "C" },
    { name = "cinquemila", model = "cinquemila", class = "C" },
    { name = "iwagen", model = "iwagen", class = "C" },
    { name = "astron", model = "astron", class = "C" },
    { name = "baller7", model = "baller7", class = "C" },
    { name = "buffalo2", model = "buffalo2", class = "C" },
    { name = "comet4", model = "comet4", class = "C" },
    { name = "komoda", model = "komoda", class = "C" },
    { name = "jugular", model = "jugular", class = "C" },
    { name = "khamelion", model = "khamelion", class = "C" },
    { name = "kuruma", model = "kuruma", class = "C" },
    { name = "omnis", model = "omnis", class = "C" },
    { name = "penumbra", model = "penumbra", class = "C" },
    { name = "raptor", model = "raptor", class = "C" },
    { name = "ruston", model = "ruston", class = "C" },
    { name = "streiter", model = "streiter", class = "C" },
    { name = "surano", model = "surano", class = "C" },
    { name = "evervstron", model = "vstr", class = "C" },
    { name = "vectre", model = "vectre", class = "C" },
    { name = "casco", model = "casco", class = "C" },
    { name = "cheetah2", model = "cheetah2", class = "C" },
    { name = "feltzer3", model = "feltzer3", class = "C" },
    { name = "gt500", model = "gt500", class = "C" },
    { name = "monroe", model = "monroe", class = "C" },
    { name = "rapidgt3", model = "rapidgt3", class = "C" },
    { name = "retinue", model = "retinue", class = "C" },
    { name = "stingergt", model = "stingergt", class = "C" },
    { name = "turismo2", model = "turismo2", class = "C" },
    { name = "cheburek", model = "cheburek", class = "C" },
    { name = "toreador", model = "toreador", class = "C" },
    { name = "vanzglad", model = "vanzglad", class = "C" },
    { name = "vanzglads", model = "vanzglads", class = "C" },
    { name = "rmodgt63", model = "rmodgt63", class = "C" },
    { name = "rmodm5e34", model = "rmodm5e34", class = "C" },
    { name = "rmodjeep", model = "rmodjeep", class = "C" },
    { name = "sharkcam", model = "sharkcam", class = "C" },
    { name = "rmodbiposto", model = "rmodbiposto", class = "C" },
    { name = "vanz745", model = "vanz745", class = "C" },
    { name = "vanzcharger", model = "vanzcharger", class = "C" },
    { name = "vanzcrowndonk", model = "vanzcrowndonk", class = "C" },
    { name = "wildtrak", model = "wildtrak", class = "C" },
    { name = "vanzelco", model = "vanzelco", class = "C" },

    ------------------------b class------------------
    { name = "kanjo", model = "kanjo", class = "B" },
    { name = "previon", model = "previon", class = "B" },
    { name = "coquette3", model = "coquette3", class = "B" },
    { name = "deviant", model = "deviant", class = "B" },
    { name = "dominator3", model = "dominator3", class = "B" },
    { name = "dominator7", model = "dominator7", class = "B" },
    { name = "dominator8", model = "dominator8", class = "B" },
    { name = "gauntlet3", model = "gauntlet3", class = "B" },
    { name = "gauntlet4", model = "gauntlet4", class = "B" },
    { name = "gauntlet5", model = "gauntlet5", class = "B" },
    { name = "tulip", model = "tulip", class = "B" },
    { name = "granger2", model = "granger2", class = "B" },
    { name = "comet7", model = "comet7", class = "B" },
    { name = "deity", model = "deity", class = "B" },
    { name = "jubilee", model = "jubilee", class = "B" },
    { name = "alpha", model = "alpha", class = "B" },
    { name = "banshee", model = "banshee", class = "B" },
    { name = "carbonizzare", model = "carbonizzare", class = "B" },
    { name = "comet2", model = "comet2", class = "B" },
    { name = "comet3", model = "comet3", class = "B" },
    { name = "comet5", model = "comet5", class = "B" },
    { name = "coquette", model = "coquette", class = "B" },
    { name = "coquette2", model = "coquette2", class = "B" },
    { name = "feltzer2", model = "feltzer2", class = "B" },
    { name = "flashgt", model = "flashgt", class = "B" },
    { name = "furoregt", model = "furoregt", class = "B" },
    { name = "gb200", model = "gb200", class = "B" },
    { name = "imorgon", model = "imorgon", class = "B" },
    { name = "issi7", model = "issi7", class = "B" },
    { name = "jester", model = "jester", class = "B" },
    { name = "jester3", model = "jester3", class = "B" },
    { name = "locust", model = "locust", class = "B" },
    { name = "lynx", model = "lynx", class = "B" },
    { name = "massacro", model = "massacro", class = "B" },
    { name = "ninef", model = "ninef", class = "B" },
    { name = "ninef2", model = "ninef2", class = "B" },
    { name = "rapidgt", model = "rapidgt", class = "B" },
    { name = "rapidgt2", model = "rapidgt2", class = "B" },
    { name = "revolter", model = "revolter", class = "B" },
    { name = "schafter3", model = "schafter3", class = "B" },
    { name = "schafter4", model = "schafter4", class = "B" },
    { name = "schwarzer", model = "schwarzer", class = "B" },
    { name = "sentinel3", model = "sentinel3", class = "B" },
    { name = "sugoi", model = "sugoi", class = "B" },
    { name = "sultan", model = "sultan", class = "B" },
    { name = "sultan2", model = "sultan2", class = "B" },
    { name = "verlierer2", model = "verlierer2", class = "B" },
    { name = "zr350", model = "zr350", class = "B" },
    { name = "calico", model = "calico", class = "B" },
    { name = "euros", model = "euros", class = "B" },
    { name = "jester4", model = "jester4", class = "B" },
    { name = "comet6", model = "comet6", class = "B" },
    { name = "growler", model = "growler", class = "B" },
    { name = "cypher", model = "cypher", class = "B" },
    { name = "sultan3", model = "sultan3", class = "B" },
    { name = "rt3000", model = "rt3000", class = "B" },
    { name = "infernus2", model = "infernus2", class = "B" },
    { name = "mamba", model = "mamba", class = "B" },
    { name = "swinger", model = "swinger", class = "B" },
    { name = "z190", model = "z190", class = "B" },
    { name = "ztype", model = "ztype", class = "B" },
    { name = "zion3", model = "zion3", class = "B" },
    { name = "as1pxxbd", model = "as1pxxbd", class = "B" },
    { name = "yarisrb", model = "yarisrb", class = "B" },
    { name = "rmodescort", model = "rmodescort", class = "B" },
    { name = "vanz34180", model = "vanz34180", class = "B" },
    { name = "vanzc8", model = "vanzc8", class = "B" },
    { name = "evanzcadiveron", model = "vanzcadi", class = "B" },
    { name = "vanzs2k", model = "vanzs2k", class = "B" },
    { name = "vanzwagon", model = "vanzwagon", class = "B" },
    { name = "vanzi8", model = "vanzi8", class = "B" },
    { name = "2018zl1", model = "2018zl1", class = "B" },
    { name = "BENTAYGAST", model = "BENTAYGAST", class = "B" },
    { name = "foxsci", model = "foxsci", class = "B" },

    ----------------------a class------------------
    { name = "champion", model = "champion", class = "A" },
    { name = "buffalo4", model = "buffalo4", class = "A" },
    { name = "bestiagts", model = "bestiagts", class = "A" },
    { name = "coquette4", model = "coquette4", class = "A" },
    { name = "coquette4", model = "coquette4", class = "A" },
    { name = "elegy", model = "elegy", class = "A" },
    { name = "elegy2", model = "elegy2", class = "A" },
    { name = "italigto", model = "italigto", class = "A" },
    { name = "neo", model = "neo", class = "A" },
    { name = "neon", model = "neon", class = "A" },
    { name = "paragon", model = "paragon", class = "A" },
    { name = "pariah", model = "pariah", class = "A" },
    { name = "penumbra2", model = "penumbra2", class = "A" },
    { name = "schlagen", model = "schlagen", class = "A" },
    { name = "seven70", model = "seven70", class = "A" },
    { name = "specter", model = "specter", class = "A" },
    { name = "italirsx", model = "italirsx", class = "A" },
    { name = "banshee2", model = "banshee2", class = "A" },
    { name = "bullet", model = "bullet", class = "A" },
    { name = "furia", model = "furia", class = "A" },
    { name = "infernus", model = "infernus", class = "A" },
    { name = "italigtb", model = "italigtb", class = "A" },
    { name = "sc1", model = "sc1", class = "A" },
    { name = "sheava", model = "sheava", class = "A" },
    { name = "sultanrs", model = "sultanrs", class = "A" },
    { name = "taipan", model = "taipan", class = "A" },
    { name = "turismor", model = "turismor", class = "A" },
    { name = "vacca", model = "vacca", class = "A" },
    { name = "voltic", model = "voltic", class = "A" },
    { name = "xa21", model = "xa21", class = "A" },
    { name = "zentorno", model = "zentorno", class = "A" },
    { name = "amstreetgt", model = "amstreetgt", class = "A" },
    { name = "carsonswbc6", model = "carsonswbc6", class = "A" },
    { name = "draftgpr", model = "draftgpr", class = "A" },
    { name = "rmodbacalar", model = "rmodbacalar", class = "A" },
    { name = "rmoddarki8", model = "rmoddarki8", class = "A" },
    { name = "rmode63s", model = "rmode63s", class = "A" },
    { name = "rmodlfa", model = "rmodlfa", class = "A" },
    { name = "rmodf40", model = "rmodf40", class = "A" },
    { name = "rmodrs6", model = "rmodrs6", class = "A" },
    { name = "rmodsennagtr", model = "rmodsennagtr", class = "A" },
    { name = "rmodsuprapandem", model = "rmodsuprapandem", class = "A" },
    { name = "vanzcamaro", model = "vanzcamaro", class = "A" },
    { name = "rmodz350pandem", model = "rmodz350pandem", class = "A" },
    { name = "2019gt3rs", model = "2019gt3rs", class = "A" },
    { name = "vanz350z", model = "vanz350z", class = "A" },
    { name = "rmodbentley1", model = "rmodbentley1", class = "A" },
    { name = "bmwm5f90", model = "bmwm5f90", class = "A" },
    { name = "brabus500", model = "brabus500", class = "A" },
    { name = "venatus", model = "venatus", class = "A" },

    --------------------s class--------------
    { name = "ignus", model = "ignus", class = "S" },
    { name = "prototipo", model = "prototipo", class = "S" },
    { name = "tyrant", model = "tyrant", class = "S" },
    { name = "zeno", model = "zeno", class = "S" },
    { name = "deveste", model = "deveste", class = "S" },
    { name = "infernus2", model = "infernus2", class = "S" },
    { name = "adder", model = "adder", class = "S" },
    { name = "autarch", model = "autarch", class = "S" },
    { name = "cheetah", model = "cheetah", class = "S" },
    { name = "cyclone", model = "cyclone", class = "S" },
    { name = "entity2", model = "entity2", class = "S" },
    { name = "entityxf", model = "entityxf", class = "S" },
    { name = "emerus", model = "emerus", class = "S" },
    { name = "fmj", model = "fmj", class = "S" },
    { name = "gp1", model = "gp1", class = "S" },
    { name = "italigtb2", model = "italigtb2", class = "S" },
    { name = "krieger", model = "krieger", class = "S" },
    { name = "nero", model = "nero", class = "S" },
    { name = "nero2", model = "nero2", class = "S" },
    { name = "osiris", model = "osiris", class = "S" },
    { name = "penetrator", model = "penetrator", class = "S" },
    { name = "pfister811", model = "pfister811", class = "S" },
    { name = "reaper", model = "reaper", class = "S" },
    { name = "t20", model = "t20", class = "S" },
    { name = "tempesta", model = "tempesta", class = "S" },
    { name = "tezeract", model = "tezeract", class = "S" },
    { name = "thrax", model = "thrax", class = "S" },
    { name = "tigon", model = "tigon", class = "S" },
    { name = "vagner", model = "vagner", class = "S" },
    { name = "visione", model = "visione", class = "S" },
    { name = "zorrusso", model = "zorrusso", class = "S" },
    { name = "r8byv", model = "r8byv", class = "S" },
    { name = "rmod918spyder", model = "rmod918spyder", class = "S" },
    { name = "rmodbolide", model = "rmodbolide", class = "S" },
    { name = "rmodessenza", model = "rmodessenza", class = "S" },
    { name = "rmodessenza", model = "rmodessenza", class = "S" },
    { name = "rmodgtr50", model = "rmodgtr50", class = "S" },
    { name = "rmodlp670", model = "rmodlp670", class = "S" },
    { name = "rmodporsche918", model = "rmodporsche918", class = "S" },
    { name = "vanzhuracan", model = "vanzhuracan", class = "S" },
    { name = "rmodbugatti", model = "rmodbugatti", class = "S" },
    { name = "demonboi", model = "demonboi", class = "S" },
    { name = "foxleggera", model = "foxleggera", class = "S" },
    { name = "r35", model = "r35", class = "S" },
    { name = "bnr32", model = "bnr32", class = "S" },
    { name = "fk8", model = "fk8", class = "S" },
}