Crafting = {
	Tools = {
		[1] = { ['mechanic_tools'] = { ['iron'] = 1, } },
		[2] = { ['toolbox'] = { ['iron'] = 1, } },
		[3] = { ['ducttape'] = { ['plastic'] = 1, } },
		[4] = { ['paintcan'] = { ['aluminum'] = 1, } },
		[5] = { ['tint_supplies'] = { ['iron'] = 1, } },
		[6] = { ['underglow_controller'] = { ['iron'] = 1, } },
		[7] = { ['cleaningkit'] = { ['rubber'] = 1, } },
		
				-- Example : Delete me --
		-- Support for multiple items in recipes --
		-- Support for multiple resulting items --
		-- Support to limit items to certain job roles --
		[8] = { ['cleaningkit'] = { ['rubber'] = 1, ["engine2"] = 1, ['plastic'] = 1 },
				["amount"] = 2, ["job"] = { ["mechanic"] = 4, ["tuner"] = 4, } },
				-- Example : Delete me --

	},
	Perform = {
		[1] = { ['turbo'] = { ['steel'] = 1, } },
		[2] = { ['car_armor'] = { ['plastic'] = 1, } },
		[3] = { ['engine1'] = { ['steel'] = 1, } },
		[4] = { ['engine2'] = { ['steel'] = 1, } },
		[5] = { ['engine3'] = { ['steel'] = 1, } },
		[6] = { ['engine4'] = { ['steel'] = 1, } },
		[7] = { ['transmission1'] = { ['steel'] = 1, } },
		[8] = { ['transmission2'] = { ['steel'] = 1, } },
		[9] = { ['transmission3'] = { ['steel'] = 1, } },
		[10] = { ['brakes1'] = { ['steel'] = 1, } },
		[11] = { ['brakes2'] = { ['steel'] = 1, } },
		[12] = { ['brakes3'] = { ['steel'] = 1, } },
		[13] = { ['suspension1'] = { ['steel'] = 1, } },
		[14] = { ['suspension2'] = { ['steel'] = 1, } },
		[15] = { ['suspension3'] = { ['steel'] = 1, } },
		[16] = { ['suspension4'] = { ['steel'] = 1, } },
		[17] = { ['bprooftires'] = { ['rubber'] = 1, } },
		[18] = { ['drifttires'] = { ['rubber'] = 1, } },
		[19] = { ['nos'] = { ['noscan'] = 1, } },
		[20] = { ['noscan'] = { ['steel'] = 1, } },
	},
	Cosmetic = {
		[1] = { ['hood'] = { ['plastic'] = 1, } },
		[2] = { ['roof'] = { ['plastic'] = 1, } },
		[3] = { ['spoiler'] = { ['plastic'] = 1, } },
		[4] = { ['bumper'] = { ['plastic'] = 1, } },
		[5] = { ['skirts'] = { ['plastic'] = 1, } },
		[6] = { ['exhaust'] = { ['iron'] = 1, } },
		[7] = { ['seat'] = { ['plastic'] = 1, } },
		[8] = { ['livery'] = { ['plastic'] = 1 }, },
		[9] = { ['tires'] = { ['rubber'] = 1, } },
		[10] = { ['horn'] = { ['plastic'] = 1, } },
		[11] = { ['internals'] = { ['plastic'] = 1, } },
		[12] = { ['externals'] = { ['plastic'] = 1, } },
		[13] = { ['customplate'] = { ['steel'] = 1, } },
		[14] = { ['headlights'] = { ['plastic'] = 1, } },
		[15] = { ['rims'] = { ['iron'] = 1, } },
		[16] = { ['rollcage'] = { ['steel'] = 1, } },
	},
}

Stores = {
	ToolItems = {
		label = Loc[Config.Lan]["stores"].tools,
		slots = 7,
		items = {
			[1] = { name = "mechanic_tools", price = 0, amount = 10, info = {}, type = "item", slot = 1, },
			[2] = { name = "toolbox", price = 0, amount = 10, info = {}, type = "item", slot = 2, },
			[3] = { name = "ducttape", price = 0, amount = 100, info = {}, type = "item", slot = 3, },
			[4] = { name = "paintcan", price = 0, amount = 50, info = {}, type = "item", slot = 4, },
			[5] = { name = "tint_supplies", price = 0, amount = 50, info = {}, type = "item", slot = 5, },
			[6] = { name = "underglow_controller", price = 0, amount = 50, info = {}, type = "item", slot = 6, },
			[7] = { name = "cleaningkit", price = 0, amount = 100, info = {}, type = "item", slot = 7, },
		},
	},
	PerformItems = {
		label = Loc[Config.Lan]["stores"].perform, 
		slots = 19,
		items = {
			[1] = { name = "turbo", price = 0, amount = 50, info = {}, type = "item", slot = 1, }, 
			[2] = { name = "engine1", price = 0, amount = 50, info = {}, type = "item", slot = 2, }, 
			[3] = { name = "engine2", price = 0, amount = 50, info = {}, type = "item", slot = 3, }, 
			[4] = { name = "engine3", price = 0, amount = 50, info = {}, type = "item", slot = 4, }, 
			[5] = { name = "engine4", price = 0, amount = 50, info = {}, type = "item", slot = 5, }, 
			[6] = { name = "transmission1", price = 0, amount = 50, info = {}, type = "item", slot = 6, },		
			[7] = { name = "transmission2", price = 0, amount = 50, info = {}, type = "item", slot = 7, },		
			[8] = { name = "transmission3", price = 0, amount = 50, info = {}, type = "item", slot = 8, },		
			[9] = { name = "brakes1", price = 0, amount = 50, info = {}, type = "item", slot = 9, },
			[10] = { name = "brakes2", price = 0, amount = 50, info = {}, type = "item", slot = 10, },
			[11] = { name = "brakes3", price = 0, amount = 50, info = {}, type = "item", slot = 11, },
			[12] = { name = "car_armor", price = 0, amount = 50, info = {}, type = "item", slot = 12, },
			[13] = { name = "suspension1", price = 0, amount = 50, info = {}, type = "item", slot = 13, },
			[14] = { name = "suspension2", price = 0, amount = 50, info = {}, type = "item", slot = 14, },
			[15] = { name = "suspension3", price = 0, amount = 50, info = {}, type = "item", slot = 15, },
			[16] = { name = "suspension4", price = 0, amount = 50, info = {}, type = "item", slot = 16, },
			[17] = { name = "bprooftires", price = 0, amount = 50, info = {}, type = "item", slot = 17, },
			[18] = { name = "drifttires", price = 0, amount = 50, info = {}, type = "item", slot = 18, },
			[19] = { name = "nos", price = 0, amount = 50, info = {}, type = "item", slot = 19, },
		},
	},
	StoreItems = {
		label = Loc[Config.Lan]["stores"].cosmetic,
		slots = 16,
		items = {
			[1] = { name = "hood", price = 0, amount = 50, info = {}, type = "item", slot = 1, },
			[2] = { name = "roof", price = 0, amount = 50, info = {}, type = "item", slot = 2, },
			[3] = { name = "spoiler", price = 0, amount = 50, info = {}, type = "item", slot = 3, },
			[4] = { name = "bumper", price = 0, amount = 50, info = {}, type = "item", slot = 4, },
			[5] = { name = "skirts", price = 0, amount = 50, info = {}, type = "item", slot = 5, },
			[6] = { name = "exhaust", price = 0, amount = 50, info = {}, type = "item", slot = 6, },
			[7] = { name = "seat", price = 0, amount = 50, info = {}, type = "item", slot = 7, },
			[8] = { name = "livery", price = 0, amount = 50, info = {}, type = "item", slot = 8, },
			[9] = { name = "tires", price = 0, amount = 50, info = {}, type = "item", slot = 9, },
			[10] = { name = "horn", price = 0, amount = 50, info = {}, type = "item", slot = 10, },
			[11] = { name = "internals", price = 0, amount = 50, info = {}, type = "item", slot = 11, },
			[12] = { name = "externals", price = 0, amount = 50, info = {}, type = "item", slot = 12, },
			[13] = { name = "customplate", price = 0, amount = 50, info = {}, type = "item", slot = 13, },
			[14] = { name = "headlights", price = 0, amount = 50, info = {}, type = "item", slot = 14, },
			[15] = { name = "rims", price = 0, amount = 100, info = {}, type = "item", slot = 15, },
			[16]= { name = "rollcage", price = 0, amount = 50, info = {}, type = "item", slot = 16, },
		},
	},
}